### ISSUE TITLE
error on rpi-updater.sh

### ISSUE THREAD

**Issue by aleale99** [mattcurrycom/Jasper-RPI-Tools#2]
I'm using your rpi3 image

the script fail during rpi-update command

### 
*** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** We're running for the first time
 *** Backing up files (this will take a few minutes)
 *** Remove old firmware backup
 *** Backing up firmware
 *** Remove old modules backup
 *** Backing up modules 4.4.11-v7+
#############################################################
This update bumps to rpi-4.4.y linux tree
Be aware there could be compatibility issues with some drivers
Discussion here:
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=144087
##############################################################
 *** Downloading specific firmware revision (this will take a few minutes)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168    0   168    0     0    288      0 --:--:-- --:--:-- --:--:--   288
100 50.6M  100 50.6M    0     0  2881k      0  0:00:17  0:00:17 --:--:-- 6270k
 *** Updating firmware
 *** Updating kernel modules
 *** depmod 4.4.12+
/usr/bin/rpi-update: riga 98: /sbin/depmod: cannot execute binary file: Formato eseguibile non valido

**Comment by mattcurrycom** [comment]
was it run with sudo?

**Comment by mattcurrycom** [comment]
I ran this on a RPI3 with no issue; but I will check.

**Comment by aleale99** [comment]
inside the script every command have its sudo
the fourth is the only that give me an error and the error is in the middle/end phase of the process of update
do i need to sudo a script with sudo inside ?

**Comment by aleale99** [comment]
same command same hw with default raspian: completed 

@testlab:~ $ sudo rpi-update
[sudo] password for : 
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
#############################################################
This update bumps to rpi-4.4.y linux tree
Be aware there could be compatibility issues with some drivers
Discussion here:
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=144087
##############################################################
 *** Downloading specific firmware revision (this will take a few minutes)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168    0   168    0     0    328      0 --:--:-- --:--:-- --:--:--   328
100 50.6M  100 50.6M    0     0  4966k      0  0:00:10  0:00:10 --:--:-- 3961k
 *** Updating firmware
 *** Updating kernel modules
 *** depmod 4.4.12+
 *** depmod 4.4.12-v7+
 *** Updating VideoCore libraries
 *** Using HardFP libraries
 *** Updating SDK
 *** Running ldconfig
 *** Storing current firmware revision
 *** Deleting downloaded files
 *** Syncing changes to disk
 *** If no errors appeared, your firmware was successfully updated to 4468c4c063c3d034821dfef4e4da00f21ea72645
 *** A reboot is needed to activate the new firmware

**Comment by mattcurrycom** [comment]
I did not see this issue; I will add it to my list of fixes for this next build.  Then I will release notes with the next build.

**Comment by mattcurrycom** [comment]
I will verify on my hardware as well.

**Comment by mattcurrycom** [comment]
But this isn't an issue with the tools here... Take it to slack / forum plz.
