### ISSUE TITLE
temperature.py missing psutil module

### ISSUE THREAD

**Issue by aleale99** [mattcurrycom/Jasper-RPI-Tools#3]
using the script  with rpi3 image i have got an error

(01:03:13)-(~/jasper_tools)->python temperature.py 
Traceback (most recent call last):
  File "temperature.py", line 1, in <module>
    import psutil

is **pip install psutil** the right solution ?
Collecting psutil
  Downloading psutil-4.2.0.tar.gz (311kB)
    100% |████████████████████████████████| 317kB 723kB/s 
Installing collected packages: psutil
  Running setup.py install for psutil ... done

**Comment by mattcurrycom** [comment]
Those are not my scripts. They are actually just RPI python examples that come with it.  I just left them in as they can be useful.  Yes you would have to install psutil to use them.
